<a href="https://colab.research.google.com/github/binittababu20-cmd/data-science/blob/main/pg5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib_inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


data = pd.read_csv('/content/cars1 - cars1.csv')
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

In [ ]:
#1.Create a Pandas Series containing the values 1, 3, 5, 6, and 8, and display it.

p = pd.Series([1, 3, 5, 6, 8])
print("Pandas Series:")
display(p)

Pandas Series:

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [ ]:
#2 Create a DataFrame from a dictionary containing the details of Country, Capital, Area, and Population for the BRICS countries, and set the row labels as BR, RU, IN, CH, and SA.

df = pd.DataFrame({
    'Country': ['Brazil', 'Russia', 'India', 'China', 'South Africa'],
    'Capital': ['Brasilia', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
    'Area': [8.516, 17.10, 3.286, 9.597, 1.221],
    'Population': [200.4, 143.5, 1252, 1357, 52.98]
})
df.index = ['BR', 'RU', 'IN', 'CH', 'SA']

display(df)

         Country    Capital    Area  Population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
#3 Read the dataset cars1.csv into a DataFrame and: o Display the complete dataset. o Display the first four records. o Display the fifth and sixth records. o Display the third row using the iloc[] method.
df = pd.read_csv('/content/cars1 - cars1.csv')
print(df.head())
print(df.tail())
print(df.iloc[4:6])
print(df.iloc[2])

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car
0       1  chevrolet chevelle malibu
1       1          buick skylark 320
2       1         plymouth satellite
3       1              amc rebel sst
4       1                ford torino
      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
193  24.0          6           200         81    3012          17.6     76
194  22.5          6           232         90    3085          17.6     76
195  29.0          4            85         52    2035          22.2     76
196  24.5          4            98         60    2164          22.1     76
197  29.0          4            90         70    1937          14.2     76

     origin                 car
193       1       ford maverick
194       1          amc hornet
195       1  chevrolet chevette
196       1     chevrolet woody
197       2           vw rabbit
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
4  17.0          8           302        140    3449          10.5     70
5  15.0          8           429        198    4341          10.0     70

   origin               car
4       1       ford torino
5       1  ford galaxie 500
mpg                           18.0
cylinders                        8
displacement                   318
horsepower                     150
weight                        3436
acceleration                  11.0
model                           70
origin                           1
car             plymouth satellite
Name: 2, dtype: object

In [ ]:
#4.Create a DataFrame containing the columns Name, Gender, and Age, and perform
#DataFrame slicing to:
#Display the first two rows.
#Display all rows from the third row onwards.

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
    'Age': [25, 30, 35, 28, 22]
})
df.index = ['A', 'B', 'C', 'D', 'E']
print(df.iloc[:3])
print(df.iloc[2:])

      Name  Gender  Age
A    Alice  Female   25
B      Bob    Male   30
C  Charlie    Male   35
      Name  Gender  Age
C  Charlie    Male   35
D    David    Male   28
E      Eve  Female   22

In [ ]:
#5 Create a Pandas Series containing four random numbers, and display:The complete Series.The values stored in the Series.The first two elements using head().The last three elements using tail().
df = pd.Series([1, 3, 5, 6, 8])
print("Pandas Series:")
print(df)
print("values in Series:")
print(df.values)
print("First two elements:")
print(df.head(2))
print("Last three elements :")
print(df.tail(3))

Pandas Series:
0    1
1    3
2    5
3    6
4    8
dtype: int64
values in Series:
[1 3 5 6 8]
First two elements:
0    1
1    3
dtype: int64
Last three elements :
2    5
3    6
4    8
dtype: int64

In [ ]:
#6 Create a DataFrame containing the columns Name, Age, and Rating, and display the following DataFrame properties: Transpose of the DataFrame. Row and column labels using axes. Data type of each column using dtypes. Whether the DataFrame is empty using empty. Number of dimensions using ndim.Shape of the DataFrame using shape.Total number of elements using size.Values stored in the DataFrame using values. Number of missing values in each column using isnull().sum().


df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 28, 22],
    'Rating': [4.5, 3.9, 4.2, 4.8, 3.7]
})
df.index = ['A', 'B', 'C', 'D', 'E']
print("DataFrame:")
display(df)
print("Transpose:")
display(df.T)
print("Row and column:")
display(df.axes)
print("Data type:")
display(df.dtypes)
print( df.empty)
print("Number of dimensions:", df.ndim)
print("Shape :", df.shape)
print("Total number of elements :", df.size)
print("Values stored in the DataFrame:")
display(df.values)
print("Number of missing values in each column :")
display(df.isnull().sum())

DataFrame:

      Name  Age  Rating
A    Alice   25     4.5
B      Bob   30     3.9
C  Charlie   35     4.2
D    David   28     4.8
E      Eve   22     3.7

Transpose:

            A    B        C      D    E
Name    Alice  Bob  Charlie  David  Eve
Age        25   30       35     28   22
Rating    4.5  3.9      4.2    4.8  3.7

Row and column:

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['Name', 'Age', 'Rating'], dtype='object')]

Data type:

Name       object
Age         int64
Rating    float64
dtype: object

False
Number of dimensions: 2
Shape : (5, 3)
Total number of elements : 15
Values stored in the DataFrame:

array([['Alice', 25, 4.5],
       ['Bob', 30, 3.9],
       ['Charlie', 35, 4.2],
       ['David', 28, 4.8],
       ['Eve', 22, 3.7]], dtype=object)

Number of missing values in each column :

Name      0
Age       0
Rating    0
dtype: int64